version: '3'
services:
  server:
    build: .
    ports:
      - "3200:3000"
    links: 
      - db   
  db:
    image: mongo:5.0
    container_name: mongoBigData
    volumes:
      - db:/data/db
    ports: 
      - "27018:27017"
    expose:
      - 27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=hector
      - MONGO_INITDB_ROOT_PASSWORD=reallydifficultpassword
      - MONGO_INITDB_DATABASE=bigData
    restart: always
volumes:
  db:
